[workspace]
members = [
    "opentelemetry-*",
    "examples/*",
]
resolver = "2"

[profile.bench]
# https://doc.rust-lang.org/cargo/reference/profiles.html#bench
# See function names in profiling reports.
# 2/true is too much, 0 is not enough, 1 is just right for back traces
debug = 1

[workspace.dependencies]
opentelemetry = "0.25"
opentelemetry-appender-tracing = "0.25"
opentelemetry-http = "0.25"
opentelemetry-proto = { version = "0.25", default-features = false }
opentelemetry_sdk = { version = "0.25", default-features = false }
opentelemetry-stdout = "0.25"
opentelemetry-semantic-conventions = "0.25"
